- name: Application Installation
  hosts: localhost

  vars:
          aptget:
                  - "i3"
                  - "i3blocks"
                  - "compton"
                  - "feh"
                  - "rofi"
                  - "cool-retro-term"
                  - "git"
                  - "thunar"
                  - "ranger"
                  - "vim"

  tasks:

          - name: Install AptGet
            apt:
                    name: "{{aptget}}"


