---
- name: Folder Creation and File Movement
  hosts: localhost

  vars:
          folders:
                  - "~/Pictures/wallpaper"
                  - "~/I3_config/compton"
                  - "~/I3_config/i3blocks"


  tasks:

          - name: Create Folders
            file:
                    path: "{{ item }}"
                    recurse: yes
                    state: directory
            with_items: "{{ folders }}"
