---
- name: Folder Creation and File Movement
  hosts: localhost

  vars:
          folders:
                  - "~/Pictures/wallpaper"
                  - "~/I3_config/compton"
                  - "~/I3_config/i3blocks"

          files:
                  - [ '../files/config', '~/.config/i3' ]
                  - [ '../files/comptonconfig.conf', '~/I3_config/compton']
                  - [ '../files/i3blocks.conf', '~/I3_config/i3blocks' ]
                  - [ '../files/logo.png', '~/Pictures/wallpaper' ]

          destinations:
                  - "~/.config/i3"
                  - "~/I3_config/compton"
                  - "~/I3_config/i3blocks"


  tasks:

          - name: Create Folders
            file:
                    path: "{{ item }}"
                    recurse: yes
                    state: directory
            with_items: "{{ folders }}"

          - name: Copy Files
            ansible.builtin.copy:
                    src: "{{ item.0 }}"
                    dest: "{{ item.1 }}"
            with_items:
                    - "{{ files }}"
                    
